<?php 

if (function_exists('acf_add_local_field_group')) {

    acf_add_local_field_group(array(
    'key' => 'group_pitea_hero_module',
    'title' => __('Pitea Hero Module', 'modularity-pitea-hero'),
    'fields' => array(
        0 => array(
            'key' => 'field_pitea_hero_hide_title',
            'label' => __('Hide Title', 'modularity-pitea-hero'),
            'name' => 'mod_hide_title',
            'type' => 'true_false',
            'instructions' => __('Hide the module title on the frontend', 'modularity-pitea-hero'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'ui' => 1,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        1 => array(
            'key' => 'field_pitea_hero_background_image',
            'label' => __('Background Image', 'modularity-pitea-hero'),
            'name' => 'mod_piteahero_background_image',
            'type' => 'image',
            'instructions' => __('Select the background image for the hero section', 'modularity-pitea-hero'),
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
            'preview_size' => 'medium',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
        2 => array(
            'key' => 'field_pitea_hero_overlay_opacity',
            'label' => __('Overlay Opacity', 'modularity-pitea-hero'),
            'name' => 'mod_piteahero_overlay_opacity',
            'type' => 'range',
            'instructions' => __('Adjust the darkness of the overlay (0 = transparent, 100 = fully dark)', 'modularity-pitea-hero'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 50,
            'min' => 0,
            'max' => 100,
            'step' => 5,
            'prepend' => '',
            'append' => '%',
        ),
        3 => array(
            'key' => 'field_pitea_hero_heading',
            'label' => __('Heading', 'modularity-pitea-hero'),
            'name' => 'mod_piteahero_heading',
            'type' => 'text',
            'instructions' => __('Main heading text displayed in the hero section', 'modularity-pitea-hero'),
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        4 => array(
            'key' => 'field_pitea_hero_search_placeholder',
            'label' => __('Search Placeholder', 'modularity-pitea-hero'),
            'name' => 'mod_piteahero_search_placeholder',
            'type' => 'text',
            'instructions' => __('Placeholder text for the search input field', 'modularity-pitea-hero'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        5 => array(
            'key' => 'field_pitea_hero_buttons',
            'label' => __('Buttons', 'modularity-pitea-hero'),
            'name' => 'mod_piteahero_buttons',
            'type' => 'repeater',
            'instructions' => __('Add buttons to display in the hero section', 'modularity-pitea-hero'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => 'field_pitea_hero_button_text',
            'min' => 0,
            'max' => 12,
            'layout' => 'block',
            'button_label' => __('Add Button', 'modularity-pitea-hero'),
            'rows_per_page' => 20,
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_pitea_hero_button_icon',
                    'label' => __('Icon', 'modularity-pitea-hero'),
                    'name' => 'mod_piteahero_button_icon',
                    'type' => 'icon',
                    'instructions' => __('Select an icon for this button', 'modularity-pitea-hero'),
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'parent_repeater' => 'field_pitea_hero_buttons',
                ),
                1 => array(
                    'key' => 'field_pitea_hero_button_text',
                    'label' => __('Text', 'modularity-pitea-hero'),
                    'name' => 'mod_piteahero_button_text',
                    'type' => 'text',
                    'instructions' => __('Button label text', 'modularity-pitea-hero'),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'parent_repeater' => 'field_pitea_hero_buttons',
                ),
                2 => array(
                    'key' => 'field_pitea_hero_button_link',
                    'label' => __('Link', 'modularity-pitea-hero'),
                    'name' => 'mod_piteahero_button_link',
                    'type' => 'link',
                    'instructions' => __('Button link destination', 'modularity-pitea-hero'),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'array',
                    'parent_repeater' => 'field_pitea_hero_buttons',
                ),
            ),
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'mod-pitea-hero',
            ),
        ),
        1 => array(
            0 => array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/pitea-hero',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
));

}
